### ISSUE TITLE
Question: do we need Kalman and LSS classes

### ISSUE THREAD

**Issue by spencerlyon2** [QuantEcon/QuantEcon.py#115]
I know that in the lectures we use these two classes separately, but to me the kalman filtering routines should be methods of the LSS class that represents linear gaussian state space models.

**Comment by jstac** [comment]
Hmmm.  I guess we could do that.  It's nice to unify things. If we put Kalman routines in LSS we would need to generalize the latter to accommodate noisy updating of y_t from x_t, rather than the current deterministic rule y_t = G x_t.  But that's no big deal.

Aside: LSS isn't a great name in retrospect.  Perhaps we should rename it LinearStateSpace at the same time.

**Comment by jstac** [comment]
As per our email discussion, Kalman will subclass LSS, and the update rule for y_t will be generalized to include noise.  I still propose that we change the name LSS to LinearStateSpace.

**Comment by jstac** [comment]
New discussion of this issue can be found in #134.  This issue should be closed when #134 is merged.

**Comment by spencerlyon2** [comment]
Closing as #134 has been merged
