### ISSUE TITLE
Numpy version to fall back on in lss.py

### ISSUE THREAD

**Issue by jstac** [QuantEcon/QuantEcon.py#132]
Put in an ordinary numpy version of `simulate_linear_model` to fall back on when numba is not installed.  Better than falling back on the un-jitted current version, which doesn't use any vectorization.

**Comment by oyamad** [comment]
I would like to discuss this issue before updating PR #103 on jitting `gth_solve`.

1.
One approach is that we make it our premise that the user has Numba installed (if he/she doesn't we assume that he/she knows how to install Numba), and we avoid repeating one algorithm with two versions, one of Numba and the other of Numpy.

2.
If we decide to always prepare two versions, one way to code is as follows:
```python
def simulate_linear_model(A, x0, v, ts_length):
    A = np.asarray(A)
    n = A.shape[0]
    x = np.empty((n, ts_length))
    x[:, 0] = x0
    
    if numba_installed:
        _simulate_linear_model_jit(A, v, ts_length, n, x)
        return x
    
    # if not numba_installed
    for t in range(ts_length-1):
        x[:, t+1] = A.dot(x[:, t]) + v[:, t]
    return x

@jit(nopython=True)
def _simulate_linear_model_jit(A, v, ts_length, n, out):
    for t in range(ts_length-1):
        for i in range(n):
            out[i, t+1] = v[i, t]
            for j in range(n):
                out[i, t+1] += A[i, j] * out[j, t]
```

Another would be:
```python
def simulate_linear_model(A, x0, v, ts_length):
    # Numpy version

def _simulate_linear_model_loop(A, x0, v, ts_length):
    # Current version with loops

if numba_installed:
    simulate_linear_model = jit(_simulate_linear_model_loop)
```

The former appears to be better, since it minimizes repetition and we can make explicit the code segment in `nopython` mode (at least for this case). (There may be other possible ways.)

What do you guys think?

**Comment by jstac** [comment]
This is a very interesting discussion.  Here are my thoughts:

First, we've seen what numba can do, it's a great technology, it's under active development and it's accessible to most of our user base (since they'll be installing Anaconda).  Hence we should exploit it extensively.

For now we'll generally be optimizing existing routines. As such it shouldn't be hard to keep an alternative version, typically NumPy oriented and vectorized, for when numba is unavailable.   Hence I support option 2 of @oyamad 's proposals.  Having said that, I wouldn't be too concerned if in the future we wrote modules without a NumPy alternative, given that our time is not unlimited.  After all, the great majority of people will have numba or can easily install it.

Finally, of the two different approaches to maintaining alternative versions proposed by @oyamad, I think I prefer the second one.  It's not as clever as the first one but it's more transparent, easier to remember, and I doubt there will be a big difference in terms of lines of code.

I'd like to hear other people's opinions.

**Comment by spencerlyon2** [comment]
I agree with everything @jstac said. I like the second approach to maintaining alternative versions of the routines.

I also think we will eventually not need to support two versions for new codes.

**Comment by mmcky** [comment]
Hi All - Here are my thoughts on this. I also generally agree with the current discussion with two additional comments below.  I also think option 2 is more transparent and less confusing with one use case exception (see comment 2). 

Comment on Option 2
-----------------------------
While the ``_`` removes the numba function from the namespace which seems sensible (in IPython context etc) ... given the numba version probably shouldn't be used without numba is there any reason why we shouldn't just put all of the numba code into the ``numba_installed`` conditional to enforce grouping all of the numba applicable code?

What do you guys think if we modified the style slightly to be:

```python
def simulate_linear_model(A, x0, v, ts_length):
    # Numpy version

if numba_installed:
    def _simulate_linear_model_loop(A, x0, v, ts_length):
        # Current version with loops
    simulate_linear_model = jit(_simulate_linear_model_loop)
    #-OR-#
    @jit(nopython=True)
    def _simulate_linear_model_loop(A, x0, v, ts_length):
        # Current version with loops
````

where the numba conditional always follows the function in question. 

Alternatively in the same spirit of this style we could also choose to replace the function and reuse the docstring to unify the functions in the IPython environment. 

```python
def simulate_linear_model(A, x0, v, ts_length):
    # Numpy version

if numba_installed:
    doc = simulate_linear_model.__doc__
    def simulate_linear_model(A, x0, v, ts_length):
        # Current version with loops
    simulate_linear_model.__doc__ = doc
    simulate_linear_model = jit(_simulate_linear_model_loop)
````
I am not entirely sure what will happen to the sphinx documentation in this case though. 
Will we get two functions of the same name in the doc's?

Optimizing Sections of Functions
------------------------------------------
The first style has its use case though when the whole function doesn't require or cannot be entirely converted to numba or you want to just optimise some function specific embedded iteration (identified through a line profiler).  

Functions that make use of high level data structures (such as Pandas DataFrames) can be really great but are usually incompatible with numba. For this case I sometimes use a small sub-function that is ``numbafied`` rather than writing a whole new function for everything and pass the data in a more primitive form to the sub-function and then wrap the results back in a DataFrame etc. 

In this case I have found the following structure useful, which is pretty similar to Option 1, except with an embedded sub-function:

```python
def some_lengthy_function():
    """" docs """"
    #-Helper Function-#
    @jit
    def some_lengthy_function_specific_iteration_logic():
          #-Iteration-#
    
    #-Some Function Code-#
    #-Call to some_iteration_logic(method) that is numbafied-#
    #-Some more Function code.. -#
   
    return something_useful
````

This approach lines up well when optimising functions using a line_profiler etc. and attacks only the sections of the function that are slow - but I think is best used with numba as a dependency or we end up with conditional statements throughout the function.  However:
  1. This case can also be covered by Option 2 by re-factoring ... if we choose to enforce a single style.  
  2. Also this project so far doesn't really suffer from this issue as it primarily uses numpy arrays etc. 

Other Style Thoughts
---------------------------
1. We should probably enforce a common interface requirement for any ``python`` and ``numba`` versions in the case of having duplicate functions. Perhaps we should write a source test for this .. Can this be done in ``nosetests``?
2. Add a test requirement to ensure both function outputs are the same over time. 

I also think there are some benefits to keeping both a python and numba version for the time being (particularly if the python version already exists) as in the future the jit compiler should improve and we may eventually be able to pass the python function through numba and retain the high level python elegance.  

Once this discussion concludes - I can document the outcome in the Style guide section for http://quantecon.org/developers/

**Comment by oyamad** [comment]
Sorry, the first version of my code doesn't work when Numba is not installed, raising a NameError at `@jit`.

I edited the code in my initial comment.


@mmcky You are right, the Numba version will not be used if Numba is not installed. Also, the NumPy version is not used if Numba is installed. So yet another version would be:

Code 3
```python
if numba_installed:
    @jit
    def simulate_linear_model(A, x0, v, ts_length):
        A = np.asarray(A)
        n = A.shape[0]
        x = np.empty((n, ts_length))
        x[:, 0] = x0

        for t in range(ts_length-1):
            for i in range(n):
                x[i, t+1] = v[i, t]
                for j in range(n):
                    x[i, t+1] += A[i, j] * x[j, t]
        return x
else:  # if not numba_installed
    def simulate_linear_model(A, x0, v, ts_length):
        A = np.asarray(A)
        n = A.shape[0]
        x = np.empty((n, ts_length))
        x[:, 0] = x0

        for t in range(ts_length-1):
            x[:, t+1] = A.dot(x[:, t]) + v[:, t]
        return x
```

**Comment by albop** [comment]
It seems relatively clear that even if numba is the default, some sort of fallback must be provided. 
    - People may not have numba installed or may have a different version of it, than the one we require.
    - Non-optimized version may have a better pedagogical value.
    - Non-optimized functions can be debugged, while numba ones, are still seen by the debugger as a black box (and can't raise exceptions, for instance)

About the type of fallback that we provide there seem to be a couple of criteria to keep in mind:
    1/ if we have alternative available implementations available, we need to be able to import all of them at the same time in order to test them against each other. This is usually not a problem with numba since `jit(f).py_func` is actually `f`
    2/ we should avoid complexifying the structure of modules, so that auto-completers can still do their job. Namely, if we define a function `fun_numpy` then set `fun = fun_numpy`, the static analyser won't be able to tell how to use `fun`. This situation may be different though if there is already a function `fun` before the assignment. Then I guess, the completion `tips` maybe those of the orginal function `fun`.
    3/ it would be nice not to repeat the same docstring many time.
    4/ when a nopython numba function is available. It should be accessible directly, not encapsulated in a Python function. This is because if `f` is a nopython numba function, then `def g(x): return 2*f(x)` is also a nopython numba function so that you can build a whole stack on it, without performance loss.

To me, 1/ and 2/ rule out the option of having the definitions inside an if block. Still I don't know if there is a perfect solution.
An easy first order approach would be to change the `jit` function so that instead of failing it would return the original function. This would be easy and transparant but lead to a very slow backup solution.
Of the proposed solution the one that seems closer to a good solution (at least for points 1/-2/-4/), would be to write something like:

```python
def fun(): ...                                # reference implementation to be compiled with numba

def fun_numpy():                      # alternative implementation in numpy

copy_doc(fun, fun_numpy)

try:
    fun = jit(fun)
except:
   fun = fun_numpy()
```
or with a small amount of magic:

```python
def fun(): ...              # reference implementation to be compiled with numba

@alternate(fun)       # copy the docstring from `fun`  and keep `fun_numpy` as an attribute of `fun`
def fun_numpy():     # alternative implementation in numpy

fun = compile(fun)  
```

or with more magic:

```python
def fun(): ...              # reference implementation to be compiled with numba
def fun_numpy():     # alternative implementation in numpy

fun = compile(fun)  # based on conventions, would look for fun_numpy, use it if available and copy the docstring
```

**Comment by cc7768** [comment]
It sounds like others agree, but I think John's comment

> Having said that, I wouldn't be too concerned if in the future we wrote modules without a NumPy alternative, given that our time is not unlimited.

will eventually be the way to go. I think currently it is probably safe to not require `numba` (although I personally wouldn't be opposed to just having it be a requirement) since it is still very much in development and is constantly progressing, but eventually we should be able to expect people to satisfy that requirement. For now, I think @albop has proposed the solution (although we don't need a solution if we just require `numba`) that I like best that requires the least repetition of code which is valuable.

As far as having code for pedagogical purposes, I think that falls more into the scope of the website than the library. I think the code for the library and the website will eventually have a decoupling of some sort. It actually might be valuable as we develop to write the pedagogical versions first and then keep those somewhere to be exposed to the website while within the library we just have the optimized versions (but keeping the interface constant so it feels the same). That brings us back to some disadvantages of maintaining two sets of code and questions about where things go (both of which we have had a few short discussions about).

**Comment by jstac** [comment]
Very interesting discussion, as usual.

@mmcky Nice suggestions.  I agree that we want to be pulling out just small parts of methods and functions for optimization.  For example, in lss.py I didn't optimize the whole `simulate` method inside the class.  I pulled out the main loop from the method and made it a separate function to target for optimization.  Then the `simulate` method calls the function.  

Good idea to summarize this discussion in the style guide when we conclude.

As usual @albop raises lots of great points.  I like his implementation 1 since it's immediately clear what's happening.  (I'm a bit scared of magic too.)   In lss.py I guess I added the logic

```python
numba_installed = True
try:
    from numba import jit
except ImportError:
   numba_installed = False
   numba_warning_message = "Numba import failed. Falling back to non-optimized routine."
   warnings.warn(numba_warning_message, UserWarning)
```

because I wanted a one off warning message (which should be unified, see #133) when numba import fails, rather than a warning message every time  someone tries to use the function.

Responding to @cc7768 , I agree that we should move to having numba as a requirement --- it's too good not to exploit, and people will be attracted to the library if it's fast.  Then we get more developers and a better library.  What's more, optimization is fun!  Let's keep an eye on numba and try to decide a good time.

I also second the idea that the library and the website should start to decouple.  It's already a good time to do this.  We can just be more selective about the code we show in the website, and direct more advanced users to GitHub when they want to know more.

**Comment by mmcky** [comment]
@albop good point on testing. The other ways would make that task much more difficult. This then implicitly requires that numba be the base implementation (as you have commented in your example) and the numpy / python version to be secondary implementations to retain access to all functions for testing ``fun()`` against ``fun_numpy()``. This also gives a good sense for the natural hierarchy. 

One minor point though is I liked how @oyamad had prepended  an ``_`` on the alternative specifications of duplicate functions. This way these alternative specifications are not cluttering up the namespace when using IPython.

**Comment by oyamad** [comment]
As another concrete example for discussion I implemented a Numba version for [mc_sample_path](https://github.com/QuantEcon/QuantEcon.py/blob/master/quantecon/mc_tools.py#L279); see Issue #137.
