### ISSUE TITLE
Remove dependence on matplotlib

### ISSUE THREAD

**Issue by jstac** [QuantEcon/QuantEcon.py#262]
At least some modules pull in `matplotlib`, such as this one:

https://github.com/QuantEcon/QuantEcon.py/blob/master/quantecon/arma.py

Let's get rid of this dependency if possible.  One way to do this when we have functions that generate plots is to have them take an `axes` instance as an argument and write to it.

(This could be added to the contributions style guide.)

**Comment by davidrpugh** [comment]
@jstac I agree with the sentiment, but worry doesn't writing functions and methods that depend on an axes instance leaves us with an implicit dependency on `matplotlib` rather than the explicit dependency that we have now.

How much code is actually using plotting functionality? There are so many good plotting libraries out there and given that preferences over optimal plotting libraries are quite idiosyncratic (i.e., there is no dominant visualization library) perhaps we should  consider removing all plotting code. 

Code we have now could be moved to examples that demonstrate usage of the core library. This would leave us with less code to maintain in the long run and leave the choice of data viz tooling entirely to the end user.

**Comment by jstac** [comment]
@davidrpugh  That's probably a good idea.  I just ran a search and only `arma.py` is importing Matplotlib.  If there's no objection, then I'll pull it out and put it in QuantEcon.applications.

Thanks ;-)

**Comment by cc7768** [comment]
Was just thinking about this -- Long story which I'll generate another thread for. It doesn't look like we ever removed this dependency. Are people still in favor of removing this dep? (I am)

**Comment by jstac** [comment]
@cc7768 Yes, definitely, I just haven't had time...

**Comment by davidrpugh** [comment]
Agreed!

**Comment by oyamad** [comment]
Done by #330 and #331.

**Comment by natashawatkins** [comment]
Seems we can close this @mmcky? `matplotlib` only returns files in the docs and something related to sphinxext

**Comment by mmcky** [comment]
indeed. Thanks @natashawatkins
