### ISSUE TITLE
Wiki Testing ... Latex Matrix Support?

### ISSUE THREAD

**Issue by sanguineturtle** [QuantEcon/QuantEcon.py#30]
Does Github markdown allow the inclusion of Latex? 
The Wiki on Writing Tests doesn't parse the matrices correctly (using $$$) in the simple test example.

**Comment by yaniv256** [comment]
No. It [seems](https://github.com/gollum/gollum/issues/288) not in the near future. I suggest either something lightweight like [torchpad](https://yaniv256.torchpad.com/) or going full armur and firing a Mediawiki with a [MarkdownSyntax extension](http://www.mediawiki.org/wiki/Extension:MarkdownSyntax). I'll be working on a proof of concept for the latter, if there is interest. The major benefits would be Talk pages and email notifications, I presume. Does anyone know of other good alternatives?

**Comment by yaniv256** [comment]
The Mediawiki powered [test wiki](http://yaniv-benami.com/mediawiki/index.php/Main_Page) is up and running, served from Amazon web Services. Come say hi!

**Comment by mmcky** [comment]
Hi Yaniv - thanks. I will head over there this afternoon and check it out.
Is there a big advantage to running our own AWS hosted wiki page beyond the
math?
I think getting math and latex style support would be great for
discussions.

**Comment by yaniv256** [comment]
We now have IPython Notebook uploads to the test wiki. There are a few benefits. [Read](http://yaniv-benami.com/mediawiki/index.php/Main_Page#IPython_Notebooks) all about it.

The darn thing fought back because it looks into the uploaded file to verify MIME and botchs completely on notebooks. I had to tweak the Mediawiki source in a couple of places to disable that. I'm not sure notebook uploads can't be done with a pristine installation but I tried and tried and it just fails. The flags are there for the user to set, but they don't work.

**Comment by albop** [comment]
I don't really get the benefit of hosting notebooks on the wiki rather than storing them elsewhere, given that we use nbviewer for them (git is excellent an people should learn it. otherwise you also leave them in a dropbox or virtually anywhere).
About the math missing in github, I don't read the public issue https://github.com/github/markup/issues/274 in the same way. It doesn't sound like they have dismissed math formulas forever. They say they are aware that there is a strong demand for it. Considering how efficient the github workflow has proven to be, one would need other good reasons to switch to a different solution.
To me the ideal solution would be git-based, (i.e. without a database) and easily integrable in the website. @mmcky : When I look at the current wiki pages http://quantecon.org/wiki/, there is no information about how to edit them. I assume they are generated from the github wiki pages. Is that right ?

**Comment by albop** [comment]
I just noticed that the gollum's wiki server (used by github) has a --mathjax-config option. Maybe it would be possible to setup a server that would run it and and edit the github wiki. Then we don't have to change anything to the current setup. Just add another editing option.

**Comment by yaniv256** [comment]
@albop,

This is not either or. You can use both. Some users will learn git and will prefer a pull request. Some won't. You can chose to reach out to the latter, or you can chose not to. We don't really need GitHub either. We can live great with a site, zip downloads and email. But we won't generate as many user contributions that way.

**Comment by yaniv256** [comment]
@albop,

Gollum does sound like a good option. Sorry I forgot to mention it. However, I never installed it before, so no comparative advantage for me there.

**Comment by davidrpugh** [comment]
I agree with @albop and I would strongly dispute the contention that we can
live without git and GitHub.  The lack of consistent use of good version
control practices has led to too much published computational work in
economics being un-replicable/un-reproducible. I think it is important that
we set a high standard for the use of version control "best-practices" in
our library.

**Comment by yaniv256** [comment]
@davidrpugh,

Sorry. I was not clear enough. I did not mean to say we don't need git and GitHub. What I meant to say is that if you do not value reaching out for user contributions you might as well take down your GitHub repository and live with a site, zip downloads, a mailing list, and email pull requests that you will merge into your local git. You know, like they used to.

**Comment by mmcky** [comment]
@albop Thanks for you comment re: http://quant-econ.org/wiki. Strictly speaking it isn't quite a wiki yet (in the sense of interacting with it via the browser) as it is currently statically generated. These pages were converted from the github wiki (markdown files) and live in the QuantEcon.site repo. We can make changes to them in the QuantEcon.site repo via PR etc. 

@yaniv256 I think the mediawiki idea is an interesting idea (thanks for your proof of concept) - but at this stage I am a bit hesitant to suggest we have multiple Wiki's as it might become more difficult for the project to manage information in multiple locations - and we then run the risk of having two "communities". My opinion is that it is good to centralise around one tool. If the math becomes difficult to live without on the github wiki then we should revisit this idea (or the gollum idea). All of the other tools (Sphinx, Readthedocs etc.) all handle math well. So the github wiki is the only one left out at the moment. @yaniv256 You are certainly welcome to keep trying out the mediawiki software as a proof of concept - if you wish. Thanks for bringing this option to our attention. 

My suggestion is we can leave this issue open to track this and revisit this infrastructure as needs of the project evolves.

**Comment by cc7768** [comment]
Small typo.  The website is quantecon.org instead of quant-econ.org

**Comment by yaniv256** [comment]
@mmcky and @albop,

Good. I just wanted to show it is not hard to come up with something more usable than the GitHub wiki, at least until they bring math back. Now that this is done, I rebranded the test wiki as my personal wiki. I think I'll keep it online and you are all welcome to use it as yet another collaboration tool, if you want. By the way, I just found that [Pandoc](http://johnmacfarlane.net/pandoc/try/) makes transitions from Markdown to MediaWiki Markup and back pretty seamless, so I think a wiki like this can be more useful for your projects than you guys give it credit, even as just a temporary sloution, but that is just one user's opinion.

**Comment by mmcky** [comment]
I see the referenced github issue is now closed on march 04th with comment ``This issue can't be resolved by a change to the code in this project, so I'm going to close this issue``.

For ``quantecon`` - changes to the wiki can be submitted through git on the ``php`` pages in ``wiki/``. Working towards a build environment through markdown. Closing this issue re: math support.
