### ISSUE TITLE
TEST: Add tests for game_theory/lemke_howson.py

### ISSUE THREAD

**Issue by mmcky** [QuantEcon/QuantEcon.py#302]
Coverage

```
game_theory/lemke_howson.py            152    122    20%
```

This has a similar issue to #300. Coverage is driven by internal private functions. As long as all internal functions are testing through ``lemke_howson()`` calls we should probably add ``# pragma: no cover`` to internal functions to fix the coverage statistics.

**Comment by oyamad** [comment]
@mmcky Thanks for opening these issues on testing.

The decrease in the coverage value is in fact not because of the privateness, but because jitted functions with `nopython=True` are not "covered"; see https://github.com/QuantEcon/QuantEcon.py/pull/144#issuecomment-98728630.

But yes, fine with me to exclude private functions that are jitted with `nopython=True`.

**Comment by mmcky** [comment]
Thanks @oyamad. I have pushed a branch that updates ``.coveragerc`` to skip ``@jit`` functions in the coverage statistics. This regex approach moves ``lemke_howson.py`` to 80+%

Perhaps I should fine tune from ``@jit`` to ``@jit(.*nopython=True)``
