### ISSUE TITLE
Failed to import LinearStateSpace

### ISSUE THREAD

**Issue by AngelaChang119** [QuantEcon/QuantEcon.py#513]
from quantecon import LinearStateSpace
  File "/usr/local/lib/python2.7/site-packages/quantecon/game_theory/normal_form_game.py", line 471
    return NE[0] @ D @ NE[1] > tol
                 ^
SyntaxError: invalid syntax

Environment:
Python 2.7.15 + IPython 5.8.0

**Comment by cc7768** [comment]
The issue is that we no longer support anything less than Python 3.5. One reason we chose to do this is that we choose to make use of the `@` operator for matrix multiplication within the library for readability reasons.

Try upgrading Python and let us know whether it still is broken (though it looks like this error comes from the `@` operator not being defined in Python 2.7).

**Comment by mmcky** [comment]
thanks @cc7768. @AngelaChang119 please let us know how you go with `python>=3.5`. We typically recommend using: https://www.anaconda.com/distribution/

**Comment by AngelaChang119** [comment]
> The issue is that we no longer support anything less than Python 3.5. One reason we chose to do this is that we choose to make use of the `@` operator for matrix multiplication within the library for readability reasons.
> 
> Try upgrading Python and let us know whether it still is broken (though it looks like this error comes from the `@` operator not being defined in Python 2.7).

> thanks @cc7768. @AngelaChang119 please let us know how you go with `python>=3.5`. We typically recommend using: https://www.anaconda.com/distribution/

Thank you very much! I install python 3.7.5 and successfully import quantecon.

**Comment by mmcky** [comment]
good news. Thanks @AngelaChang119
